const String privacy = "Introduction"
    "Car Consultant values your privacy and is committed to protecting your personal information. This Privacy Policy outlines how we collect, use, and safeguard your data when you use the Car Consultant app."
    "Information We Collect"
    "Personal Information: We may collect personal data when you register, such as your name, phone number, email address, and payment details."
    "Non-Personal Information: We may also collect non-personal data, such as device type, operating system, usage patterns, and location data (if permitted)."
    "How We Use Your Information"
    "We use your information to:"
    "Provide, maintain, and improve the services of the Car Consultant app."
    "Facilitate payments for services booked through the app."
    "Communicate with you regarding updates, promotions, or important notices."
    "Personalize your experience by offering relevant content and service recommendations."
    "Information Sharing and Disclosure"
    "We may share your data with:"
    "Third-party Service Providers: To facilitate payment processing, scheduling, and other essential services (e.g., consultants and repair shops)."
    "Legal Compliance: If required by law or to protect our rights."
    "Business Transfers: In the event of a merger, acquisition, or sale of assets, your data may be transferred as part of that transaction."
    "Data Security"
    "We take your data security seriously and implement appropriate measures such as:"
    "Data encryption for all sensitive information during transactions."
    "Regular security audits to ensure the integrity of our systems. However, no method of transmission or storage is completely secure, and we cannot guarantee absolute security."
    "User Rights"
    "As a user, you have the right to:"
    "Access: Request access to the personal information we hold about you."
    "Correction: Request that we correct any inaccuracies in your personal data."
    "Deletion: Request that we delete your account and personal information."
    "Opt-out: Opt-out of receiving promotional communications at any time."
    "Data Retention"
    "We retain your personal information for as long as your account is active or as needed to provide you with services. Once you request deletion, we will remove your data in accordance with legal obligations and our data retention policy."
    "Cookies and Tracking Technologies"
    "We use cookies and similar tracking technologies to enhance user experience, collect usage data, and deliver personalized content. You can adjust your device settings to manage or block cookies, but this may affect the app's functionality."
    "Children’s Privacy"
    "Our app is not intended for use by individuals under the age of 18. We do not knowingly collect personal information from minors. If you believe a child has provided us with personal data, please contact us, and we will take appropriate action."
    "Changes to this Privacy Policy"
    "We may update this Privacy Policy periodically. We will notify users of any significant changes through the app or via email. Your continued use of the app after such changes indicates acceptance of the updated policy."
    "Contact Information"
    "If you have any questions or concerns regarding this Privacy Policy, please contact us at:"
    "•Email: [support@carconsultant.app]";
